// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_l7SlM5e4foO59Jo7n8UEj-CW0DYpi3A',
    appId: '1:30269175897:web:3fb88eb38378d863959948',
    messagingSenderId: '30269175897',
    projectId: 'testmentor-41a06',
    authDomain: 'testmentor-41a06.firebaseapp.com',
    databaseURL: 'https://testmentor-41a06-default-rtdb.firebaseio.com',
    storageBucket: 'testmentor-41a06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpcCtfcvPD8MjKhfY7GFKftyoU90sVDds',
    appId: '1:30269175897:android:3b2f5a5a9c0c449e959948',
    messagingSenderId: '30269175897',
    projectId: 'testmentor-41a06',
    databaseURL: 'https://testmentor-41a06-default-rtdb.firebaseio.com',
    storageBucket: 'testmentor-41a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYcgUz1HNeB-pPZgSb7MViRbtFocWcI5A',
    appId: '1:30269175897:ios:a37da27038bd2222959948',
    messagingSenderId: '30269175897',
    projectId: 'testmentor-41a06',
    databaseURL: 'https://testmentor-41a06-default-rtdb.firebaseio.com',
    storageBucket: 'testmentor-41a06.appspot.com',
    iosClientId: '30269175897-hf69be7vpfi1ui6le9pg63rhp3ldd0kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.testmentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYcgUz1HNeB-pPZgSb7MViRbtFocWcI5A',
    appId: '1:30269175897:ios:a37da27038bd2222959948',
    messagingSenderId: '30269175897',
    projectId: 'testmentor-41a06',
    databaseURL: 'https://testmentor-41a06-default-rtdb.firebaseio.com',
    storageBucket: 'testmentor-41a06.appspot.com',
    iosClientId: '30269175897-hf69be7vpfi1ui6le9pg63rhp3ldd0kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.testmentor',
  );
}
